language: node_js

node_js: 10

env:
  - NODE_ENV=ci

install:
  - npm ci

script:
  - npm run build -- --base /perfect-colour

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
